package cn.bjfu.ws.model;

import java.util.Date;

public class StudentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.id
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.uid
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.type
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Long number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.major
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.class_name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.sex
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.master
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String master;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.instructor
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String instructor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.native_place
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String nativePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.student_origin
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String studentOrigin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.nation
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.religion
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String religion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.politics_status
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String politicsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.dormitory
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String dormitory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.phone_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Long phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.id_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String idNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.emergency_contact
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String emergencyContact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.emergency_phone
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String emergencyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.gmt_create
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.gmt_modified
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.ewards_punishments
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String ewardsPunishments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.mental_state
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String mentalState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.tutoring_case
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String tutoringCase;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_info.remark
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.id
     *
     * @return the value of student_info.id
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.id
     *
     * @param id the value for student_info.id
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.uid
     *
     * @return the value of student_info.uid
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.uid
     *
     * @param uid the value for student_info.uid
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.name
     *
     * @return the value of student_info.name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.name
     *
     * @param name the value for student_info.name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.type
     *
     * @return the value of student_info.type
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.type
     *
     * @param type the value for student_info.type
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.number
     *
     * @return the value of student_info.number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.number
     *
     * @param number the value for student_info.number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.major
     *
     * @return the value of student_info.major
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.major
     *
     * @param major the value for student_info.major
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.class_name
     *
     * @return the value of student_info.class_name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.class_name
     *
     * @param className the value for student_info.class_name
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.sex
     *
     * @return the value of student_info.sex
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.sex
     *
     * @param sex the value for student_info.sex
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.master
     *
     * @return the value of student_info.master
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.master
     *
     * @param master the value for student_info.master
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setMaster(String master) {
        this.master = master == null ? null : master.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.instructor
     *
     * @return the value of student_info.instructor
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getInstructor() {
        return instructor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.instructor
     *
     * @param instructor the value for student_info.instructor
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setInstructor(String instructor) {
        this.instructor = instructor == null ? null : instructor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.native_place
     *
     * @return the value of student_info.native_place
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.native_place
     *
     * @param nativePlace the value for student_info.native_place
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.student_origin
     *
     * @return the value of student_info.student_origin
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getStudentOrigin() {
        return studentOrigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.student_origin
     *
     * @param studentOrigin the value for student_info.student_origin
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setStudentOrigin(String studentOrigin) {
        this.studentOrigin = studentOrigin == null ? null : studentOrigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.nation
     *
     * @return the value of student_info.nation
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.nation
     *
     * @param nation the value for student_info.nation
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.religion
     *
     * @return the value of student_info.religion
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getReligion() {
        return religion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.religion
     *
     * @param religion the value for student_info.religion
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setReligion(String religion) {
        this.religion = religion == null ? null : religion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.politics_status
     *
     * @return the value of student_info.politics_status
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getPoliticsStatus() {
        return politicsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.politics_status
     *
     * @param politicsStatus the value for student_info.politics_status
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setPoliticsStatus(String politicsStatus) {
        this.politicsStatus = politicsStatus == null ? null : politicsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.dormitory
     *
     * @return the value of student_info.dormitory
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getDormitory() {
        return dormitory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.dormitory
     *
     * @param dormitory the value for student_info.dormitory
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setDormitory(String dormitory) {
        this.dormitory = dormitory == null ? null : dormitory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.phone_number
     *
     * @return the value of student_info.phone_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Long getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.phone_number
     *
     * @param phoneNumber the value for student_info.phone_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setPhoneNumber(Long phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.id_number
     *
     * @return the value of student_info.id_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.id_number
     *
     * @param idNumber the value for student_info.id_number
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.emergency_contact
     *
     * @return the value of student_info.emergency_contact
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.emergency_contact
     *
     * @param emergencyContact the value for student_info.emergency_contact
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact == null ? null : emergencyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.emergency_phone
     *
     * @return the value of student_info.emergency_phone
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getEmergencyPhone() {
        return emergencyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.emergency_phone
     *
     * @param emergencyPhone the value for student_info.emergency_phone
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setEmergencyPhone(String emergencyPhone) {
        this.emergencyPhone = emergencyPhone == null ? null : emergencyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.gmt_create
     *
     * @return the value of student_info.gmt_create
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.gmt_create
     *
     * @param gmtCreate the value for student_info.gmt_create
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.gmt_modified
     *
     * @return the value of student_info.gmt_modified
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.gmt_modified
     *
     * @param gmtModified the value for student_info.gmt_modified
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.ewards_punishments
     *
     * @return the value of student_info.ewards_punishments
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getEwardsPunishments() {
        return ewardsPunishments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.ewards_punishments
     *
     * @param ewardsPunishments the value for student_info.ewards_punishments
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setEwardsPunishments(String ewardsPunishments) {
        this.ewardsPunishments = ewardsPunishments == null ? null : ewardsPunishments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.mental_state
     *
     * @return the value of student_info.mental_state
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getMentalState() {
        return mentalState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.mental_state
     *
     * @param mentalState the value for student_info.mental_state
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setMentalState(String mentalState) {
        this.mentalState = mentalState == null ? null : mentalState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.tutoring_case
     *
     * @return the value of student_info.tutoring_case
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getTutoringCase() {
        return tutoringCase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.tutoring_case
     *
     * @param tutoringCase the value for student_info.tutoring_case
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setTutoringCase(String tutoringCase) {
        this.tutoringCase = tutoringCase == null ? null : tutoringCase.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_info.remark
     *
     * @return the value of student_info.remark
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_info.remark
     *
     * @param remark the value for student_info.remark
     *
     * @mbg.generated Wed Mar 04 23:20:23 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}