package cn.bjfu.ws.model;

import java.util.Date;

public class UserToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.id
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.uid
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.token
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.id
     *
     * @return the value of user_token.id
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.id
     *
     * @param id the value for user_token.id
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.gmt_create
     *
     * @return the value of user_token.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.gmt_create
     *
     * @param gmtCreate the value for user_token.gmt_create
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.gmt_modified
     *
     * @return the value of user_token.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.gmt_modified
     *
     * @param gmtModified the value for user_token.gmt_modified
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.uid
     *
     * @return the value of user_token.uid
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.uid
     *
     * @param uid the value for user_token.uid
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.token
     *
     * @return the value of user_token.token
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.token
     *
     * @param token the value for user_token.token
     *
     * @mbg.generated Wed Mar 04 13:44:20 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}